### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by AVAILABLEUSERNAME00000** [Extravi/Installer#2]
does ur shader surrport Mac cuz it no work if not can you add it to Mac cuz that would be nice bro

**Comment by Extravi** [comment]
ReShade does not work on MacOS, but you can try PlayOnMac or Wine to see if you can get it to work, or you can dual boot Windows and MacOS.

https://www.playonmac.com/en/
https://support.apple.com/en-ca/HT201468
https://www.winehq.org/
