### ISSUE TITLE
Something keeps deleting the shaders installer before i can open it

### ISSUE THREAD

**Issue by ghost** [Extravi/Installer#3]
ok so there's this antivirus on my PC called Norton 360, and it keeps deleting the shaders before i can open it. what should i do?

**Comment by Extravi** [comment]
because its a new file thats why i just updated it again https://github.com/Extravi/Installer/releases/tag/v7.0.0

**Comment by ghost** [comment]
thank you! also i managed to open it before my antivirus could delete it

**Comment by Extravi** [comment]
nice
