### ISSUE TITLE
Byfron

### ISSUE THREAD

**Issue by tlaus1** [Extravi/Installer#5]
I'm not sure why, but my best guess is that the Extravi Reshade is not working because of the Byfron Update. I was just wondering if you are working on a new version for Reshade that bypasses Byfron.

**Comment by TomerGamerTV** [comment]
Same it doesn't work

**Comment by Extravi** [comment]
no there isn't a version of reshade that can bypass byfron

**Comment by Extravi** [comment]
https://github.com/Extravi/Installer/issues/6
