### ISSUE TITLE
im working on a nvidia only version of this for byfron

### ISSUE THREAD

**Issue by Extravi** [Extravi/Installer#6]

**Comment by Extravi** [comment]
https://github.com/Extravi/Installer/issues/5

**Comment by Extravi** [comment]
ill also likely work on tools to make the nvidia version simple etc

**Comment by Extravi** [comment]
it wont be prefect or work the same or even look the same but its something and its better than nothing

**Comment by texwt** [comment]
Happy to hear that 😆 you might be the only one to work on shaders after the byfron update... Thanks for your work and time

**Comment by Extravi** [comment]
np video below
https://github.com/Extravi/Installer/assets/98912029/fa798194-72f5-4b5d-8579-a96909017c21



> Happy to hear that 😆 you might be the only one to work on shaders after the byfron update... Thanks for your work and time

**Comment by Extravi** [comment]
https://github.com/Extravi/Bloxshade

**Comment by Extravi** [comment]
made a new installer
